### ISSUE TITLE
CarPlay app required Flutter App open first?

### ISSUE THREAD

**Issue by ankiimation** [oguzhnatly/flutter_carplay#12]
I think CarPlay app can start itself with out starting Flutter App first

**Comment by oguzhnatly** [comment]
Hello @ankiimation,

That method you mentioned is not recommended because we set the root template of the CarPlay App in the Flutter App's initial state. As a result, if the flutter app is never opened after installation, you may see a black screen or crash directly. The CarPlay app may be displayed successfully after the first opening of the flutter app, but it may not function properly. That is why it is recommended to use the app. 

I also highly recommend creating a graphic art for the carplay app when it is not open, as this will notify the user of the need to open the app first.

**Comment by ankiimation** [comment]
> Hello @ankiimation,
> 
> That method you mentioned is not recommended because we set the root template of the CarPlay App in the Flutter App's initial state. As a result, if the flutter app is never opened after installation, you may see a black screen or crash directly. The CarPlay app may be displayed successfully after the first opening of the flutter app, but it may not function properly. That is why it is recommended to use the app.
> 
> I also highly recommend creating a graphic art for the carplay app when it is not open, as this will notify the user of the need to open the app first.

ok bro, love it

**Comment by snipd-mikel** [comment]
Hi @ankiimation,

I have found a way to launch the Flutter app when starting the app through the CarPlay interface when the app is not running on the foreground. The solution is based on this blog post: https://adapptor.com.au/blog/enhance-existing-apps-with-carplay where they solve it for ReactNative.

The main idea is to move the `FlutterEngine` creation to the `AppDelegate`, which will be run when the app is launched from anywhere (CarPlay or device). We can run the `FlutterEngine` in headless mode, so the dart code can run before the engine is attached to any actual view (which happens when launching the app first on the CarPlay). Then, on the `SceneDelegate` we reuse the engine and attach it to the actual view.

So the `AppDelegate.swift` will be like this:

```swift
import UIKit
import Flutter

let flutterEngine = FlutterEngine(name: "SharedEngine", project: nil, allowHeadlessExecution: true)

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application( _ application: UIApplication,
                             didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    
    flutterEngine.run()
    GeneratedPluginRegistrant.register(with: flutterEngine)

    return super.application(application, didFinishLaunchingWithOptions: launchOptions);
    
  }
}
```

and the `SceneDelegate.swift` like this:

```swift
@available(iOS 13.0, *)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {

        guard let windowScene = scene as? UIWindowScene else { return }

        window = UIWindow(windowScene: windowScene)
        let controller = FlutterViewController.init(engine: flutterEngine, nibName: nil, bundle: nil)
        window?.rootViewController = controller
        window?.makeKeyAndVisible()
    }
}

```

With this we have the dart code running when the user launches the app from the CarPlay interface. However, some changes are needed on this plugin as well, as it will fail to update the `rootInterface` if it was null when launching the `CarPlayScene`. The solution here is to modify the [FlutterCarplayPluginSceneDelegate](https://github.com/oguzhnatly/flutter_carplay/blob/master/ios/Classes/FlutterCarplayPluginSceneDelegate.swift) so it doesn't set the `interfaceController` to `nil` if the `rootTemplate` is not set at startup. You have to replace the `templateApplicationScene` with the following snippet:

```swift
func templateApplicationScene(_ templateApplicationScene: CPTemplateApplicationScene,
                                didConnect interfaceController: CPInterfaceController) {
    FlutterCarPlaySceneDelegate.interfaceController = interfaceController
    
    SwiftFlutterCarplayPlugin.onCarplayConnectionChange(status: FCPConnectionTypes.connected)
    let rootTemplate = SwiftFlutterCarplayPlugin.rootTemplate
    
    if rootTemplate != nil {
      FlutterCarPlaySceneDelegate.interfaceController?.setRootTemplate(rootTemplate!, animated: SwiftFlutterCarplayPlugin.animated, completion: nil)
    }
  }
```

Then on your dart code, after setting the root template using `FlutterCarplay.setRootTemplate` you have to force the plugin to update the displayed template using: `_flutterCarplay.forceUpdateRootTemplate();`

With this you should be able to run the app when the user opens it on the CarPlay.

I have a branch with this changes here: https://github.com/snipd-mikel/flutter_carplay/commit/a4a201c0629b180d622dec289891dae94f131bd3

@oguzhnatly Would it be possible to merge the changes onto the main repository? Only the ones on this file [FlutterCarplayPluginSceneDelegate](https://github.com/oguzhnatly/flutter_carplay/blob/master/ios/Classes/FlutterCarplayPluginSceneDelegate.swift) are actually needed to be included on the plugin. The rest of the changes could be part of the README. If you are interested I can work on a PR to have this ready.

**Comment by ankiimation** [comment]
But there some issues when we run Flutter app on CarPlay without open it on the device first:
- dart:ui: I can't draw images(assets, network)

**Comment by snipd-mikel** [comment]
Thanks for the info. I haven't yet run into many issues, as most of what I need on the CarPlay is not related to Flutter UI components. However, I encountered some issue where after some async event the UI was not being updated (I needed that to start the authentication flow) . I had to manually call `WidgetsBinding.instance.scheduleForcedFrame();` to force it to update.

**Comment by vanlooverenkoen** [comment]
I don't think this issue should be closed. At least it should be documented. On what the recommended way should be to implement this.

**Comment by mwyczarski** [comment]
I don't think this should be closed either. Have any of you encountered a bug, where there is a black screen after a splash? I think that's because initializing Flutter renderer overrides the splash, but I don't know how could I solve that

**Comment by RedC4ke** [comment]
TO ANYONE WHO STRUGGLES WITH SPLASHSCREENS ON IOS

I've found out that the only thing needed here is to add 
`controller.loadDefaultSplashScreenView()` 
in @snipd-mikel solution after controller initialization. Now it works like a charm :)

**Comment by RedC4ke** [comment]
Also I don't think that this is an ideal solution, won't it create two engines sometimes? Bc I keep getting some old view for a split second before the splashscreen

**Comment by harryandroiddev** [comment]
After these changes i cannot login with facebook  when i have the fb app installed .

**Comment by zhushenwudi** [comment]
> Thanks for the info. I haven't yet run into many issues, as most of what I need on the CarPlay is not related to Flutter UI components. However, I encountered some issue where after some async event the UI was not being updated (I needed that to start the authentication flow) . I had to manually call `WidgetsBinding.instance.scheduleForcedFrame();` to force it to update.

I use GetX for status management, but when I try to open CarPlay first and then start the mobile app, I find that GetX is invalid. Have you ever experienced a similar situation?

**Comment by marcolettieri** [comment]
@snipd-mikel  is a good solution but i think @RedC4ke  is right and it will create two engines. i have also the same issue of @harryandroiddev with facebook login. There is some solution to prevent the creation of unneeded engine? for example is it possible to detect in finishlaunching and use engine or self for the plugins?

Facebook Login crashes because of Thread 1: Swift runtime failure: force unwrapped a nil value:
`    private func logIn(result: @escaping FlutterResult, permissions: [String]) {
        let viewController = (UIApplication.shared.delegate?.window??.rootViewController)!
`

**Comment by marcolettieri** [comment]
@harryandroiddev  i've solved just with this in SceneDelegate:
    ```
     if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
            // Set the window property of the AppDelegate
            appDelegate.window = window
        }
```

**Comment by Stewioie** [comment]
If I create a new enginge in AppDelegateSwift its mess up with Firebase too

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:56:41)
#2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:33:55)
#3      _logToFirebase (package:app_chameleon/main.dart:59:23)
#4      _RootZone.runBinary (dart:async/zone.dart:1666:54)
#5      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#6      _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#7      _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)

**Comment by derrik-fleming** [comment]
It doesn't seem like this works anymore. After attempting to use the solution mentioned in this [comment](https://github.com/oguzhnatly/flutter_carplay/issues/12#issuecomment-1150229720) in my app and having no success, I pulled down the linked repo and found I got the same results. App will open on CarPlay, it appears `main` is executed, but none of the CarPlay methods function as intended, results in a blank screen until the app is closed on CarPlay, opened on mobile, and then re-opened on CarPlay.

Am I missing something?

**Comment by richanshah** [comment]
it is not working for me

**Comment by ragul-steamA** [comment]
Can some one help me to show some UI to open app in mobile, instead of blank screen. If app not opened.

**Comment by swiftymf** [comment]
> It doesn't seem like this works anymore. After attempting to use the solution mentioned in this [comment](https://github.com/oguzhnatly/flutter_carplay/issues/12#issuecomment-1150229720) in my app and having no success, I pulled down the linked repo and found I got the same results. App will open on CarPlay, it appears `main` is executed, but none of the CarPlay methods function as intended. The result is a blank screen until the app is closed on CarPlay, opened on mobile, and then re-opened on CarPlay.
> 
> Am I missing something?

I'm seeing the same behavior @snipd-mikel are you still using your fork of this repo? Any advice you can send our way to help fix this issue? Thanks!

**Comment by derrik-fleming** [comment]
> I'm seeing the same behavior @snipd-mikel are you still using your fork of this repo? Any advice you can send our way to help fix this issue? Thanks!

@swiftymf I was actually able to get this to work. I don't think I made any changes to code, but I can verify at some point.

Are you testing on a Simulator or a physical device? 

Run `clean` maybe(?) if you haven't already, try a different Simulator or device, wipe your pub cache. I'm pretty sure it just started working for me at some point after doing one (or maybe a combination of the above).

**Comment by swiftymf** [comment]
> > I'm seeing the same behavior [@snipd-mikel](https://github.com/snipd-mikel) are you still using your fork of this repo? Any advice you can send our way to help fix this issue? Thanks!
> 
> [@swiftymf](https://github.com/swiftymf) I was actually able to get this to work. I don't think I made any changes to code, but I can verify at some point.
> 
> Are you testing on a Simulator or a physical device?
> 
> Run `clean` maybe(?) if you haven't already, try a different Simulator or device, wipe your pub cache. I'm pretty sure it just started working for me at some point after doing one (or maybe a combination) of the above.
> 
> Edit: Also, make sure you haven't wrapped your call to set the root template in a condition based on the connection state. One thing that I found is that my app never received the connection status changed event when launched from CarPlay first (without additional changes).

Omg it was pebkac...I had some logic set up that was not running but also doing a null check which was preventing the CarPlay app from loading anything. Thanks for your help anyway!

**Comment by zhushenwudi** [comment]
This tripartite library is also used in my project. According to the reply in issue, the implementation effect is good, but by no means complete.The current effect is to open the carplay application without opening the mobile app, which only realizes the most basic function. At present, it has some problems, such as: 1. When using getx. The layout and font size may be scaled and distorted. 2. The instance may not be able to run according to flutter's standard life cycle because its implementation is to set flutterEnergy as a global variable.

You can refer to my open source project
https://github.com/LoveLiveMusicPlayer/LoveLiveMusicPlayerMobile

The important thing to look at is the implementation of the application function of AppDelegate.swift in swift and the scene function of SceneDelegate.swift

**Comment by zippka224** [comment]
> Also I don't think that this is an ideal solution, won't it create two engines sometimes? Bc I keep getting some old view for a split second before the splashscreen

did you ever find a fix for this issue?

**Comment by EArminjon** [comment]
Should be fixed in [Release 1.1.0 #66](https://github.com/oguzhnatly/flutter_carplay/pull/66).
